name: Playwright Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci

      - run: npx playwright install --with-deps

      - name: Start Application
        run: |
          npm start &
          npx wait-on http://localhost:3000

      - name: Run Tests
        run: npm run test:e2e
